"""Portuguese cities and towns."""

CITIES = [
    # Major cities
    "Lisboa",
    "Porto",
    "Braga",
    "Coimbra",
    "Faro",
    "Funchal",
    "Ponta Delgada",
    "Aveiro",
    "Évora",
    "Setúbal",
    "Viseu",
    "Viana do Castelo",
    "Vila Real",
    "Bragança",
    "Guarda",
    "Castelo Branco",
    "Leiria",
    "Santarém",
    "Portalegre",
    "Beja",
    # Notable towns
    "Guimarães",
    "Sintra",
    "Cascais",
    "Óbidos",
    "Tavira",
    "Lagos",
    "Tomar",
    "Batalha",
    "Alcobaça",
    "Nazaré",
    "Peniche",
    "Ericeira",
    "Sesimbra",
    "Arrábida",
    "Marvão",
    "Monsaraz",
    "Monsanto",
    "Sortelha",
    "Piódão",
    "Amarante",
    "Lamego",
    "Chaves",
    "Ponte de Lima",
    "Valença",
    "Silves",
    "Elvas",
    "Estremoz",
    "Vila Nova de Milfontes",
    "Costa Nova",
    "Miranda do Douro",
    "Peso da Régua",
    "Pinhão",
    "Vila Real de Santo António",
    "Sagres",
    "Albufeira",
    "Portimão",
    "Vilamoura",
    "Caldas da Rainha",
    "Torres Vedras",
    "Palmela",
    "Angra do Heroísmo",
]

# Map to Wikipedia articles
WIKIPEDIA = {
    "Lisboa": "Lisbon",
    "Porto": "Porto",
    "Braga": "Braga",
    "Coimbra": "Coimbra",
    "Faro": "Faro, Portugal",
    "Funchal": "Funchal",
    "Ponta Delgada": "Ponta Delgada",
    "Aveiro": "Aveiro, Portugal",
    "Évora": "Évora",
    "Setúbal": "Setúbal",
    "Viseu": "Viseu",
    "Viana do Castelo": "Viana do Castelo",
    "Vila Real": "Vila Real, Portugal",
    "Bragança": "Bragança, Portugal",
    "Guarda": "Guarda, Portugal",
    "Castelo Branco": "Castelo Branco, Portugal",
    "Leiria": "Leiria",
    "Santarém": "Santarém, Portugal",
    "Portalegre": "Portalegre, Portugal",
    "Beja": "Beja, Portugal",
    "Guimarães": "Guimarães",
    "Sintra": "Sintra",
    "Cascais": "Cascais",
    "Óbidos": "Óbidos, Portugal",
    "Tavira": "Tavira",
    "Lagos": "Lagos, Portugal",
    "Tomar": "Tomar",
    "Batalha": "Batalha, Portugal",
    "Alcobaça": "Alcobaça, Portugal",
    "Nazaré": "Nazaré, Portugal",
    "Peniche": "Peniche, Portugal",
    "Ericeira": "Ericeira",
    "Sesimbra": "Sesimbra",
    "Arrábida": "Arrábida Natural Park",
    "Marvão": "Marvão",
    "Monsaraz": "Monsaraz",
    "Monsanto": "Monsanto (Idanha-a-Nova)",
    "Sortelha": "Sortelha",
    "Piódão": "Piódão",
    "Amarante": "Amarante, Portugal",
    "Lamego": "Lamego",
    "Chaves": "Chaves, Portugal",
    "Ponte de Lima": "Ponte de Lima",
    "Valença": "Valença, Portugal",
    "Silves": "Silves, Portugal",
    "Elvas": "Elvas",
    "Estremoz": "Estremoz",
    "Vila Nova de Milfontes": "Vila Nova de Milfontes",
    "Costa Nova": "Costa Nova",
    "Miranda do Douro": "Miranda do Douro",
    "Peso da Régua": "Peso da Régua",
    "Pinhão": "Pinhão",
    "Vila Real de Santo António": "Vila Real de Santo António",
    "Sagres": "Sagres, Portugal",
    "Albufeira": "Albufeira",
    "Portimão": "Portimão",
    "Vilamoura": "Vilamoura",
    "Caldas da Rainha": "Caldas da Rainha",
    "Torres Vedras": "Torres Vedras",
    "Palmela": "Palmela",
    "Angra do Heroísmo": "Angra do Heroísmo",
}

# Region tags
REGIONS = {
    "Lisboa": "Estremadura",
    "Porto": "Douro Litoral",
    "Braga": "Minho",
    "Coimbra": "Beira Litoral",
    "Faro": "Algarve",
    "Funchal": "Madeira",
    "Ponta Delgada": "Açores",
    "Aveiro": "Beira Litoral",
    "Évora": "Alentejo",
    "Setúbal": "Estremadura",
    "Viseu": "Beira Alta",
    "Viana do Castelo": "Minho",
    "Vila Real": "Trás-os-Montes",
    "Bragança": "Trás-os-Montes",
    "Guarda": "Beira Alta",
    "Castelo Branco": "Beira Baixa",
    "Leiria": "Estremadura",
    "Santarém": "Ribatejo",
    "Portalegre": "Alto Alentejo",
    "Beja": "Baixo Alentejo",
    "Guimarães": "Minho",
    "Sintra": "Estremadura",
    "Cascais": "Estremadura",
    "Óbidos": "Estremadura",
    "Tavira": "Algarve",
    "Lagos": "Algarve",
    "Tomar": "Ribatejo",
    "Batalha": "Estremadura",
    "Alcobaça": "Estremadura",
    "Nazaré": "Estremadura",
    "Peniche": "Estremadura",
    "Ericeira": "Estremadura",
    "Sesimbra": "Estremadura",
    "Arrábida": "Estremadura",
    "Marvão": "Alto Alentejo",
    "Monsaraz": "Alentejo",
    "Monsanto": "Beira Baixa",
    "Sortelha": "Beira Alta",
    "Piódão": "Beira Alta",
    "Amarante": "Douro Litoral",
    "Lamego": "Douro",
    "Chaves": "Trás-os-Montes",
    "Ponte de Lima": "Minho",
    "Valença": "Minho",
    "Silves": "Algarve",
    "Elvas": "Alto Alentejo",
    "Estremoz": "Alentejo",
    "Vila Nova de Milfontes": "Alentejo Litoral",
    "Costa Nova": "Beira Litoral",
    "Miranda do Douro": "Trás-os-Montes",
    "Peso da Régua": "Douro",
    "Pinhão": "Douro",
    "Vila Real de Santo António": "Algarve",
    "Sagres": "Algarve",
    "Albufeira": "Algarve",
    "Portimão": "Algarve",
    "Vilamoura": "Algarve",
    "Caldas da Rainha": "Estremadura",
    "Torres Vedras": "Estremadura",
    "Palmela": "Estremadura",
    "Angra do Heroísmo": "Açores",
}
