"""Portuguese Primeira Liga football clubs (2025-26 season)."""

CLUBS = [
    "Benfica",
    "Porto",
    "Sporting CP",
    "Braga",
    "Vitoria Guimaraes",
    "Santa Clara",
    "Casa Pia",
    "Moreirense",
    "Famalicao",
    "Gil Vicente",
    "Rio Ave",
    "Estoril",
    "Arouca",
    "Boavista",
    "Nacional",
    "AVS",
    "Estrela Amadora",
    "Farense",
]

# Logos available in main memi repo
LOGOS = {
    "Benfica": "/static/logos/benfica.png",
    "Porto": "/static/logos/porto.png",
    "Sporting CP": "/static/logos/sporting_cp.png",
    "Braga": "/static/logos/braga.png",
    "Vitoria Guimaraes": "/static/logos/vitoria_guimaraes.png",
    "Santa Clara": "/static/logos/santa_clara.png",
    "Casa Pia": "/static/logos/casa_pia.png",
    "Moreirense": "/static/logos/moreirense.png",
    "Famalicao": "/static/logos/famalicao.png",
    "Gil Vicente": "/static/logos/gil_vicente.png",
    "Rio Ave": "/static/logos/rio_ave.png",
    "Estoril": "/static/logos/estoril.png",
    "Arouca": "/static/logos/arouca.png",
    "Boavista": "/static/logos/boavista.png",
    "Nacional": "/static/logos/nacional.png",
    "AVS": "/static/logos/avs.png",
    "Estrela Amadora": "/static/logos/estrela_amadora.png",
    "Farense": "/static/logos/farense.png",
}

# City where each club is based
TAGS = {
    "Benfica": "Lisboa",
    "Porto": "Porto",
    "Sporting CP": "Lisboa",
    "Braga": "Braga",
    "Vitoria Guimaraes": "Guimarães",
    "Santa Clara": "Ponta Delgada",
    "Casa Pia": "Lisboa",
    "Moreirense": "Moreira de Cónegos",
    "Famalicao": "Vila Nova de Famalicão",
    "Gil Vicente": "Barcelos",
    "Rio Ave": "Vila do Conde",
    "Estoril": "Estoril",
    "Arouca": "Arouca",
    "Boavista": "Porto",
    "Nacional": "Funchal",
    "AVS": "Vila das Aves",
    "Estrela Amadora": "Amadora",
    "Farense": "Faro",
}
