"""Portuguese traditional food and dishes."""

FOOD = [
    "Pastel de nata",
    "Bacalhau à Brás",
    "Francesinha",
    "Caldo verde",
    "Sardinha assada",
    "Arroz de marisco",
    "Cataplana",
    "Pastéis de Belém",
    "Bifana",
    "Cozido à portuguesa",
    "Açorda",
    "Alheira",
    "Queijo da Serra",
    "Arroz de pato",
    "Pão de ló",
    "Bolo de arroz",
    "Travesseiro de Sintra",
    "Ovos moles de Aveiro",
    "Tripas à moda do Porto",
    "Leitão da Bairrada",
    # Main dishes
    "Bacalhau à Gomes de Sá",
    "Bacalhau com natas",
    "Feijoada à transmontana",
    "Chanfana",
    "Arroz de cabidela",
    "Rojões",
    "Migas",
    "Polvo à lagareiro",
    "Caldeirada",
    "Arroz de tamboril",
    "Cabrito assado",
    # Snacks
    "Peixinhos da horta",
    "Rissóis",
    "Croquetes",
    "Pataniscas de bacalhau",
    "Caracóis",
    "Presunto",
    "Chouriço",
    "Moelas",
    # Sweets and desserts
    "Toucinho do céu",
    "Leite-creme",
    "Arroz doce",
    "Serradura",
    "Bola de Berlim",
    "Queijada de Sintra",
    "Pastel de Tentúgal",
    "Pudim Abade de Priscos",
    "Torta de Azeitão",
    # Cheese
    "Queijo de Azeitão",
    "Queijo de São Jorge",
    # Regional specialities
    "Papas de sarrabulho",
    "Açorda alentejana",
    "Migas à alentejana",
    "Ensopado de borrego",
    # Drinks
    "Vinho do Porto",
    "Ginjinha",
    "Licor Beirão",
]
