"""Portuguese republic figures (1910 onwards)."""

PRESIDENTS = [
    # First Republic (1910–1926)
    "Manuel de Arriaga",
    "Teófilo Braga",
    "Bernardino Machado",
    "Sidónio Pais",
    "João do Canto e Castro",
    "António José de Almeida",
    "Manuel Teixeira Gomes",
    "Bernardino Machado (2.º mandato)",
    # Estado Novo dictatorship (1926–1974)
    "Óscar Carmona",
    "Francisco Craveiro Lopes",
    "Américo Tomás",
    # Third Republic (1974–)
    "António de Spínola",
    "Francisco da Costa Gomes",
    "António Ramalho Eanes",
    "Mário Soares",
    "Jorge Sampaio",
    "Aníbal Cavaco Silva",
    "Marcelo Rebelo de Sousa",
]

FIGURES = [
    # Politics
    "António de Oliveira Salazar",
    "Marcelo Caetano",
    "Humberto Delgado",
    "Aristides de Sousa Mendes",
    "Álvaro Cunhal",
    "Mário Soares",
    "Sá Carneiro",
    "Adelino da Palma Carlos",
    "Otelo Saraiva de Carvalho",
    "Salgueiro Maia",
    "António Guterres",
    # Literature
    "Fernando Pessoa",
    "José Saramago",
    "Sophia de Mello Breyner Andresen",
    "Miguel Torga",
    "Florbela Espanca",
    "Aquilino Ribeiro",
    "José Régio",
    "Vergílio Ferreira",
    "António Lobo Antunes",
    "Agustina Bessa-Luís",
    "Eugénio de Andrade",
    "Herberto Helder",
    "Natália Correia",
    "José Cardoso Pires",
    # Music
    "Amália Rodrigues",
    "Carlos Paredes",
    "Zeca Afonso",
    "Mariza",
    "Dulce Pontes",
    "Madredeus",
    "Carlos do Carmo",
    # Cinema and arts
    "Manoel de Oliveira",
    "Paula Rego",
    "Maria Helena Vieira da Silva",
    "Júlio Pomar",
    "Almada Negreiros",
    # Science
    "Egas Moniz",
    "Abel Salazar",
    # Sports
    "Eusébio",
    "Cristiano Ronaldo",
    "José Mourinho",
    "Luís Figo",
    "Rosa Mota",
    "Carlos Lopes",
    "Fernando Peyroteo",
]

ALL = PRESIDENTS + FIGURES

# Map Portuguese names to English Wikipedia article titles
WIKIPEDIA = {
    # Presidents
    "Manuel de Arriaga": "Manuel de Arriaga",
    "Teófilo Braga": "Teófilo Braga",
    "Bernardino Machado": "Bernardino Machado",
    "Sidónio Pais": "Sidónio Pais",
    "João do Canto e Castro": "João do Canto e Castro",
    "António José de Almeida": "António José de Almeida",
    "Manuel Teixeira Gomes": "Manuel Teixeira Gomes",
    "Bernardino Machado (2.º mandato)": "Bernardino Machado",
    "Óscar Carmona": "Óscar Carmona",
    "Francisco Craveiro Lopes": "Francisco Craveiro Lopes",
    "Américo Tomás": "Américo Tomás",
    "António de Spínola": "António de Spínola",
    "Francisco da Costa Gomes": "Francisco da Costa Gomes",
    "António Ramalho Eanes": "António Ramalho Eanes",
    "Mário Soares": "Mário Soares",
    "Jorge Sampaio": "Jorge Sampaio",
    "Aníbal Cavaco Silva": "Aníbal Cavaco Silva",
    "Marcelo Rebelo de Sousa": "Marcelo Rebelo de Sousa",
    # Figures
    "António de Oliveira Salazar": "António de Oliveira Salazar",
    "Marcelo Caetano": "Marcelo Caetano",
    "Humberto Delgado": "Humberto Delgado",
    "Aristides de Sousa Mendes": "Aristides de Sousa Mendes",
    "Álvaro Cunhal": "Álvaro Cunhal",
    "Sá Carneiro": "Francisco Sá Carneiro",
    "Adelino da Palma Carlos": "Adelino da Palma Carlos",
    "Otelo Saraiva de Carvalho": "Otelo Saraiva de Carvalho",
    "Salgueiro Maia": "Salgueiro Maia",
    "António Guterres": "António Guterres",
    "Fernando Pessoa": "Fernando Pessoa",
    "José Saramago": "José Saramago",
    "Sophia de Mello Breyner Andresen": "Sophia de Mello Breyner Andresen",
    "Miguel Torga": "Miguel Torga",
    "Florbela Espanca": "Florbela Espanca",
    "Aquilino Ribeiro": "Aquilino Ribeiro",
    "José Régio": "José Régio",
    "Vergílio Ferreira": "Vergílio Ferreira",
    "António Lobo Antunes": "António Lobo Antunes",
    "Agustina Bessa-Luís": "Agustina Bessa-Luís",
    "Eugénio de Andrade": "Eugénio de Andrade",
    "Herberto Helder": "Herberto Helder",
    "Natália Correia": "Natália Correia",
    "José Cardoso Pires": "José Cardoso Pires",
    "Amália Rodrigues": "Amália Rodrigues",
    "Carlos Paredes": "Carlos Paredes",
    "Zeca Afonso": "Zeca Afonso",
    "Mariza": "Mariza",
    "Dulce Pontes": "Dulce Pontes",
    "Madredeus": "Madredeus",
    "Carlos do Carmo": "Carlos do Carmo",
    "Manoel de Oliveira": "Manoel de Oliveira",
    "Paula Rego": "Paula Rego",
    "Maria Helena Vieira da Silva": "Maria Helena Vieira da Silva",
    "Júlio Pomar": "Júlio Pomar",
    "Almada Negreiros": "Almada Negreiros",
    "Egas Moniz": "António Egas Moniz",
    "Abel Salazar": "Abel Salazar",
    "Eusébio": "Eusébio",
    "Cristiano Ronaldo": "Cristiano Ronaldo",
    "José Mourinho": "José Mourinho",
    "Luís Figo": "Luís Figo",
    "Rosa Mota": "Rosa Mota",
    "Carlos Lopes": "Carlos Lopes",
    "Fernando Peyroteo": "Fernando Peyroteo",
}

# Tags with dates/role
TAGS = {
    # Presidents
    "Manuel de Arriaga": "Presidente 1911–1915",
    "Teófilo Braga": "Presidente interino 1910–1911, 1915",
    "Bernardino Machado": "Presidente 1915–1917, 1925–1926",
    "Sidónio Pais": "Presidente 1917–1918",
    "João do Canto e Castro": "Presidente 1918–1919",
    "António José de Almeida": "Presidente 1919–1923",
    "Manuel Teixeira Gomes": "Presidente 1923–1925",
    "Bernardino Machado (2.º mandato)": "Presidente 1925–1926",
    "Óscar Carmona": "Presidente 1926–1951",
    "Francisco Craveiro Lopes": "Presidente 1951–1958",
    "Américo Tomás": "Presidente 1958–1974",
    "António de Spínola": "Presidente 1974",
    "Francisco da Costa Gomes": "Presidente 1974–1976",
    "António Ramalho Eanes": "Presidente 1976–1986",
    "Mário Soares": "Presidente 1986–1996",
    "Jorge Sampaio": "Presidente 1996–2006",
    "Aníbal Cavaco Silva": "Presidente 2006–2016",
    "Marcelo Rebelo de Sousa": "Presidente 2016–2026",
    # Figures
    "António de Oliveira Salazar": "Ditador, 1889–1970",
    "Marcelo Caetano": "Presidente do Conselho, 1906–1980",
    "Humberto Delgado": "General, candidato presidencial, 1906–1965",
    "Aristides de Sousa Mendes": "Cônsul, Justo entre as Nações, 1885–1954",
    "Álvaro Cunhal": "Político, líder do PCP, 1913–2005",
    "Mário Soares": "Político, 1924–2017",
    "Sá Carneiro": "Primeiro-ministro, 1934–1980",
    "Adelino da Palma Carlos": "Primeiro-ministro, 1905–1992",
    "Otelo Saraiva de Carvalho": "Capitão de Abril, 1936–2021",
    "Salgueiro Maia": "Capitão de Abril, 1944–1992",
    "António Guterres": "Secretário-geral da ONU, n. 1949",
    "Fernando Pessoa": "Poeta, 1888–1935",
    "José Saramago": "Escritor, Nobel 1998, 1922–2010",
    "Sophia de Mello Breyner Andresen": "Poetisa, 1919–2004",
    "Miguel Torga": "Escritor, 1907–1995",
    "Florbela Espanca": "Poetisa, 1894–1930",
    "Aquilino Ribeiro": "Escritor, 1885–1963",
    "José Régio": "Escritor, 1901–1969",
    "Vergílio Ferreira": "Escritor, 1916–1996",
    "António Lobo Antunes": "Escritor, n. 1942",
    "Agustina Bessa-Luís": "Escritora, 1922–2019",
    "Eugénio de Andrade": "Poeta, 1923–2005",
    "Herberto Helder": "Poeta, 1930–2015",
    "Natália Correia": "Escritora, 1923–1993",
    "José Cardoso Pires": "Escritor, 1925–1998",
    "Amália Rodrigues": "Fadista, 1920–1999",
    "Carlos Paredes": "Guitarrista, 1925–2004",
    "Zeca Afonso": "Cantor, 1929–1987",
    "Mariza": "Fadista, n. 1973",
    "Dulce Pontes": "Cantora, n. 1969",
    "Madredeus": "Grupo musical, desde 1985",
    "Carlos do Carmo": "Fadista, 1939–2021",
    "Manoel de Oliveira": "Cineasta, 1908–2015",
    "Paula Rego": "Pintora, 1935–2022",
    "Maria Helena Vieira da Silva": "Pintora, 1908–1992",
    "Júlio Pomar": "Pintor, 1926–2018",
    "Almada Negreiros": "Artista, 1893–1970",
    "Egas Moniz": "Médico, Nobel 1949, 1874–1955",
    "Abel Salazar": "Médico e artista, 1889–1946",
    "Eusébio": "Futebolista, 1942–2014",
    "Cristiano Ronaldo": "Futebolista, n. 1985",
    "José Mourinho": "Treinador, n. 1963",
    "Luís Figo": "Futebolista, n. 1972",
    "Rosa Mota": "Maratonista, n. 1958",
    "Carlos Lopes": "Atleta, 1947–2024",
    "Fernando Peyroteo": "Futebolista, 1918–1978",
}
