"""Portuguese rivers."""

RIVERS = [
    "Tejo",
    "Douro",
    "Guadiana",
    "Mondego",
    "Minho",
    "Sado",
    "Vouga",
    "Cávado",
    "Lima",
    "Ave",
    "Tâmega",
    "Zêzere",
    "Nabão",
    "Lis",
    "Arade",
    "Gilão",
    "Paiva",
    "Côa",
    "Sabor",
    "Corgo",
    "Águeda",
    "Dão",
    "Alva",
    "Tua",
    "Sousa",
    "Vez",
    "Mira",
    "Ocreza",
    "Pônsul",
]

# Map to English Wikipedia articles
WIKIPEDIA = {
    "Tejo": "Tagus",
    "Douro": "Douro",
    "Guadiana": "Guadiana",
    "Mondego": "Mondego",
    "Minho": "Minho (river)",
    "Sado": "Sado (river)",
    "Vouga": "Vouga (river)",
    "Cávado": "Cávado River",
    "Lima": "Lima (river)",
    "Ave": "Ave (river)",
    "Tâmega": "Tâmega",
    "Zêzere": "Zêzere (river)",
    "Nabão": "Nabão",
    "Lis": "Lis (river)",
    "Arade": "Arade (river)",
    "Gilão": "Gilão",
    "Paiva": "Paiva (river)",
    "Côa": "Côa River",
    "Sabor": "Sabor (river)",
    "Corgo": "Corgo (river)",
    "Águeda": "Águeda (river)",
    "Dão": "Dão (river)",
    "Alva": "Alva (river)",
    "Tua": "Tua (river)",
    "Sousa": "Sousa (river)",
    "Vez": "Vez (river)",
    "Mira": "Mira (river)",
    "Ocreza": "Ocreza",
    "Pônsul": "Pônsul",
}

# Notable info: length or key facts
TAGS = {
    "Tejo": "1007 km, o mais longo da Península Ibérica",
    "Douro": "897 km, nasce em Espanha",
    "Guadiana": "829 km, fronteira com Espanha",
    "Mondego": "234 km, o maior rio exclusivamente português",
    "Minho": "300 km, fronteira norte com Espanha",
    "Sado": "180 km, estuário em Setúbal",
    "Vouga": "148 km, Ria de Aveiro",
    "Cávado": "129 km, nasce na Serra do Larouco",
    "Lima": "108 km, rio do esquecimento",
    "Ave": "93 km, nasce na Serra da Cabreira",
    "Tâmega": "145 km, afluente do Douro",
    "Zêzere": "214 km, afluente do Tejo",
    "Nabão": "66 km, passa em Tomar",
    "Lis": "39 km, passa em Leiria",
    "Arade": "75 km, passa em Silves",
    "Gilão": "35 km, passa em Tavira",
    "Paiva": "110 km, afluente do Douro",
    "Côa": "140 km, gravuras rupestres",
    "Sabor": "120 km, afluente do Douro",
    "Corgo": "42 km, passa em Vila Real",
    "Águeda": "52 km, afluente do Vouga",
    "Dão": "93 km, região vinícola",
    "Alva": "110 km, afluente do Mondego",
    "Tua": "57 km, afluente do Douro",
    "Sousa": "62 km, afluente do Douro",
    "Vez": "39 km, afluente do Lima",
    "Mira": "145 km, desagua em Vila Nova de Milfontes",
    "Ocreza": "80 km, afluente do Tejo",
    "Pônsul": "81 km, afluente do Tejo",
}
