"""Portuguese monarchy figures (before 1910)."""

# First Dynasty (Burgundy), Second Dynasty (Aviz),
# Third Dynasty (Philippine), Fourth Dynasty (Braganza)

KINGS = [
    # Burgundy Dynasty (1139–1383)
    "D. Afonso Henriques",
    "D. Sancho I",
    "D. Afonso II",
    "D. Sancho II",
    "D. Afonso III",
    "D. Dinis I",
    "D. Afonso IV",
    "D. Pedro I",
    "D. Fernando I",
    # Aviz Dynasty (1385–1580)
    "D. João I",
    "D. Duarte I",
    "D. Afonso V",
    "D. João II",
    "D. Manuel I",
    "D. João III",
    "D. Sebastião I",
    "D. Henrique I",
    # Philippine Dynasty (1581–1640)
    "D. Filipe I",
    "D. Filipe II",
    "D. Filipe III",
    # Braganza Dynasty (1640–1910)
    "D. João IV",
    "D. Afonso VI",
    "D. Pedro II",
    "D. João V",
    "D. José I",
    "D. Maria I",
    "D. João VI",
    "D. Pedro IV",
    "D. Miguel I",
    "D. Maria II",
    "D. Pedro V",
    "D. Luís I",
    "D. Carlos I",
    "D. Manuel II",
]

QUEENS = [
    "D. Mafalda de Saboia",
    "D. Dulce de Aragão",
    "D. Urraca de Castela",
    "D. Mécia Lopes de Haro",
    "D. Beatriz de Castela",
    "D. Isabel de Aragão",
    "D. Beatriz de Castela (mulher de D. Afonso IV)",
    "D. Leonor Teles",
    "D. Filipa de Lencastre",
    "D. Leonor de Aragão",
    "D. Isabel de Coimbra",
    "D. Leonor de Viseu",
    "D. Isabel de Castela (mulher de D. Manuel I)",
    "D. Maria de Aragão",
    "D. Catarina de Áustria",
    "D. Luísa de Gusmão",
    "D. Maria Francisca de Saboia",
    "D. Maria Sofia de Neuburgo",
    "D. Maria Ana de Áustria",
    "D. Mariana Vitória de Espanha",
    "D. Carlota Joaquina de Bourbon",
    "D. Estefânia de Hohenzollern",
    "D. Maria Pia de Saboia",
    "D. Amélia de Orleães",
]

FIGURES = [
    # Navigators and explorers
    "Infante D. Henrique",
    "Vasco da Gama",
    "Pedro Álvares Cabral",
    "Bartolomeu Dias",
    "Fernão de Magalhães",
    "Diogo Cão",
    "Gil Eanes",
    "Afonso de Albuquerque",
    "Francisco de Almeida",
    "Duarte Pacheco Pereira",
    "Gaspar Corte-Real",
    "Pedro de Sintra",
    # Writers and poets
    "Luís de Camões",
    "Gil Vicente",
    "Fernão Lopes",
    "Garcia de Resende",
    "Bernardim Ribeiro",
    "Sá de Miranda",
    "António Ferreira",
    "Padre António Vieira",
    "Almeida Garrett",
    "Alexandre Herculano",
    "Camilo Castelo Branco",
    "Eça de Queirós",
    "Antero de Quental",
    "Cesário Verde",
    "Júlio Dinis",
    "Guerra Junqueiro",
    "Bocage",
    # Political and military figures
    "Marquês de Pombal",
    "Nuno Álvares Pereira",
    "D. Afonso de Albuquerque",
    "Conde de Castelo Melhor",
    "Conde da Ericeira",
    # Scientists and others
    "Pedro Nunes",
    "Garcia de Orta",
    "Damião de Góis",
    "Duarte Barbosa",
    # Artists
    "Nuno Gonçalves",
    "Grão Vasco",
    "Josefa de Óbidos",
    "Domingos Sequeira",
    "Machado de Castro",
]

ALL = KINGS + QUEENS + FIGURES

# Map Portuguese names to English Wikipedia article titles
WIKIPEDIA = {
    # Kings
    "D. Afonso Henriques": "Afonso I of Portugal",
    "D. Sancho I": "Sancho I of Portugal",
    "D. Afonso II": "Afonso II of Portugal",
    "D. Sancho II": "Sancho II of Portugal",
    "D. Afonso III": "Afonso III of Portugal",
    "D. Dinis I": "Denis I of Portugal",
    "D. Afonso IV": "Afonso IV of Portugal",
    "D. Pedro I": "Peter I of Portugal",
    "D. Fernando I": "Ferdinand I of Portugal",
    "D. João I": "John I of Portugal",
    "D. Duarte I": "Edward I of Portugal",
    "D. Afonso V": "Afonso V of Portugal",
    "D. João II": "John II of Portugal",
    "D. Manuel I": "Manuel I of Portugal",
    "D. João III": "John III of Portugal",
    "D. Sebastião I": "Sebastian of Portugal",
    "D. Henrique I": "Henry, King of Portugal",
    "D. Filipe I": "Philip I of Portugal",
    "D. Filipe II": "Philip II of Portugal",
    "D. Filipe III": "Philip III of Portugal",
    "D. João IV": "John IV of Portugal",
    "D. Afonso VI": "Afonso VI of Portugal",
    "D. Pedro II": "Peter II of Portugal",
    "D. João V": "John V of Portugal",
    "D. José I": "Joseph I of Portugal",
    "D. Maria I": "Maria I of Portugal",
    "D. João VI": "John VI of Portugal",
    "D. Pedro IV": "Pedro I of Brazil",
    "D. Miguel I": "Miguel I of Portugal",
    "D. Maria II": "Maria II of Portugal",
    "D. Pedro V": "Pedro V of Portugal",
    "D. Luís I": "Luís I of Portugal",
    "D. Carlos I": "Carlos I of Portugal",
    "D. Manuel II": "Manuel II of Portugal",
    # Queens
    "D. Mafalda de Saboia": "Mafalda of Savoy, Queen of Portugal",
    "D. Dulce de Aragão": "Dulce of Aragon",
    "D. Urraca de Castela": "Urraca of Castile, Queen of Portugal",
    "D. Mécia Lopes de Haro": "Mécia Lopes de Haro",
    "D. Beatriz de Castela": "Beatrice of Castile (1242–1303)",
    "D. Isabel de Aragão": "Elizabeth of Aragon",
    "D. Beatriz de Castela (mulher de D. Afonso IV)": "Beatrice of Castile (1293–1359)",
    "D. Leonor Teles": "Leonor Teles",
    "D. Filipa de Lencastre": "Philippa of Lancaster",
    "D. Leonor de Aragão": "Eleanor of Aragon, Queen of Portugal",
    "D. Isabel de Coimbra": "Isabel of Coimbra",
    "D. Leonor de Viseu": "Eleanor of Viseu",
    "D. Isabel de Castela (mulher de D. Manuel I)": "Isabella of Asturias",
    "D. Maria de Aragão": "Maria of Aragon, Queen of Portugal",
    "D. Catarina de Áustria": "Catherine of Austria, Queen of Portugal",
    "D. Luísa de Gusmão": "Luisa of Medina-Sidonia",
    "D. Maria Francisca de Saboia": "Marie Françoise of Savoy",
    "D. Maria Sofia de Neuburgo": "Maria Sophia of Neuburg",
    "D. Maria Ana de Áustria": "Maria Anna of Austria (1683–1754)",
    "D. Mariana Vitória de Espanha": "Mariana Victoria of Spain",
    "D. Carlota Joaquina de Bourbon": "Carlota Joaquina of Spain",
    "D. Estefânia de Hohenzollern": "Stephanie of Hohenzollern-Sigmaringen",
    "D. Maria Pia de Saboia": "Maria Pia of Savoy",
    "D. Amélia de Orleães": "Amélie of Orléans",
    # Figures
    "Infante D. Henrique": "Henry the Navigator",
    "Vasco da Gama": "Vasco da Gama",
    "Pedro Álvares Cabral": "Pedro Álvares Cabral",
    "Bartolomeu Dias": "Bartolomeu Dias",
    "Fernão de Magalhães": "Ferdinand Magellan",
    "Diogo Cão": "Diogo Cão",
    "Gil Eanes": "Gil Eanes",
    "Afonso de Albuquerque": "Afonso de Albuquerque",
    "Francisco de Almeida": "Francisco de Almeida",
    "Duarte Pacheco Pereira": "Duarte Pacheco Pereira",
    "Gaspar Corte-Real": "Gaspar Corte-Real",
    "Pedro de Sintra": "Pedro de Sintra",
    "Luís de Camões": "Luís de Camões",
    "Gil Vicente": "Gil Vicente (poet)",
    "Fernão Lopes": "Fernão Lopes",
    "Garcia de Resende": "Garcia de Resende",
    "Bernardim Ribeiro": "Bernardim Ribeiro",
    "Sá de Miranda": "Francisco de Sá de Miranda",
    "António Ferreira": "António Ferreira",
    "Padre António Vieira": "António Vieira",
    "Almeida Garrett": "Almeida Garrett",
    "Alexandre Herculano": "Alexandre Herculano",
    "Camilo Castelo Branco": "Camilo Castelo Branco",
    "Eça de Queirós": "Eça de Queirós",
    "Antero de Quental": "Antero de Quental",
    "Cesário Verde": "Cesário Verde",
    "Júlio Dinis": "Júlio Dinis",
    "Guerra Junqueiro": "Guerra Junqueiro",
    "Bocage": "Manuel Maria Barbosa du Bocage",
    "Marquês de Pombal": "Marquis of Pombal",
    "Nuno Álvares Pereira": "Nuno Álvares Pereira",
    "D. Afonso de Albuquerque": "Afonso de Albuquerque",
    "Conde de Castelo Melhor": "Castelo Melhor",
    "Conde da Ericeira": "Count of Ericeira",
    "Pedro Nunes": "Pedro Nunes",
    "Garcia de Orta": "Garcia de Orta",
    "Damião de Góis": "Damião de Góis",
    "Duarte Barbosa": "Duarte Barbosa",
    "Nuno Gonçalves": "Nuno Gonçalves",
    "Grão Vasco": "Grão Vasco",
    "Josefa de Óbidos": "Josefa de Óbidos",
    "Domingos Sequeira": "Domingos Sequeira",
    "Machado de Castro": "Joaquim Machado de Castro",
}

# Tags with dates/role
TAGS = {
    # Kings
    "D. Afonso Henriques": "Rei 1139–1185",
    "D. Sancho I": "Rei 1185–1211",
    "D. Afonso II": "Rei 1211–1223",
    "D. Sancho II": "Rei 1223–1247",
    "D. Afonso III": "Rei 1247–1279",
    "D. Dinis I": "Rei 1279–1325",
    "D. Afonso IV": "Rei 1325–1357",
    "D. Pedro I": "Rei 1357–1367",
    "D. Fernando I": "Rei 1367–1383",
    "D. João I": "Rei 1385–1433",
    "D. Duarte I": "Rei 1433–1438",
    "D. Afonso V": "Rei 1438–1481",
    "D. João II": "Rei 1481–1495",
    "D. Manuel I": "Rei 1495–1521",
    "D. João III": "Rei 1521–1557",
    "D. Sebastião I": "Rei 1557–1578",
    "D. Henrique I": "Rei 1578–1580",
    "D. Filipe I": "Rei 1581–1598",
    "D. Filipe II": "Rei 1598–1621",
    "D. Filipe III": "Rei 1621–1640",
    "D. João IV": "Rei 1640–1656",
    "D. Afonso VI": "Rei 1656–1683",
    "D. Pedro II": "Rei 1683–1706",
    "D. João V": "Rei 1706–1750",
    "D. José I": "Rei 1750–1777",
    "D. Maria I": "Rainha 1777–1816",
    "D. João VI": "Rei 1816–1826",
    "D. Pedro IV": "Rei 1826",
    "D. Miguel I": "Rei 1828–1834",
    "D. Maria II": "Rainha 1826–1828, 1834–1853",
    "D. Pedro V": "Rei 1853–1861",
    "D. Luís I": "Rei 1861–1889",
    "D. Carlos I": "Rei 1889–1908",
    "D. Manuel II": "Rei 1908–1910",
    # Queens
    "D. Mafalda de Saboia": "Rainha consorte 1146–1157",
    "D. Dulce de Aragão": "Rainha consorte 1174–1198",
    "D. Urraca de Castela": "Rainha consorte 1208–1220",
    "D. Mécia Lopes de Haro": "Rainha consorte 1244–1247",
    "D. Beatriz de Castela": "Rainha consorte 1253–1279",
    "D. Isabel de Aragão": "Rainha consorte 1282–1325, Rainha Santa",
    "D. Beatriz de Castela (mulher de D. Afonso IV)": "Rainha consorte 1325–1357",
    "D. Leonor Teles": "Rainha consorte 1372–1383",
    "D. Filipa de Lencastre": "Rainha consorte 1387–1415",
    "D. Leonor de Aragão": "Rainha consorte 1428–1438",
    "D. Isabel de Coimbra": "Rainha consorte 1447–1455",
    "D. Leonor de Viseu": "Rainha consorte 1471–1495",
    "D. Isabel de Castela (mulher de D. Manuel I)": "Rainha consorte 1497–1498",
    "D. Maria de Aragão": "Rainha consorte 1500–1517",
    "D. Catarina de Áustria": "Rainha consorte 1525–1557",
    "D. Luísa de Gusmão": "Rainha consorte 1640–1656",
    "D. Maria Francisca de Saboia": "Rainha consorte 1666–1683",
    "D. Maria Sofia de Neuburgo": "Rainha consorte 1687–1699",
    "D. Maria Ana de Áustria": "Rainha consorte 1708–1750",
    "D. Mariana Vitória de Espanha": "Rainha consorte 1750–1777",
    "D. Carlota Joaquina de Bourbon": "Rainha consorte 1816–1826",
    "D. Estefânia de Hohenzollern": "Rainha consorte 1858–1859",
    "D. Maria Pia de Saboia": "Rainha consorte 1862–1889",
    "D. Amélia de Orleães": "Rainha consorte 1889–1908",
    # Figures
    "Infante D. Henrique": "Navegador, 1394–1460",
    "Vasco da Gama": "Navegador, c. 1469–1524",
    "Pedro Álvares Cabral": "Navegador, c. 1467–c. 1520",
    "Bartolomeu Dias": "Navegador, c. 1450–1500",
    "Fernão de Magalhães": "Navegador, c. 1480–1521",
    "Diogo Cão": "Navegador, séc. XV",
    "Gil Eanes": "Navegador, séc. XV",
    "Afonso de Albuquerque": "Vice-rei da Índia, 1453–1515",
    "Francisco de Almeida": "Vice-rei da Índia, c. 1450–1510",
    "Duarte Pacheco Pereira": "Navegador e militar, c. 1460–c. 1533",
    "Gaspar Corte-Real": "Navegador, c. 1450–c. 1501",
    "Pedro de Sintra": "Navegador, séc. XV",
    "Luís de Camões": "Poeta, c. 1524–1580",
    "Gil Vicente": "Dramaturgo, c. 1465–c. 1536",
    "Fernão Lopes": "Cronista, c. 1380–c. 1460",
    "Garcia de Resende": "Cronista e poeta, c. 1470–1536",
    "Bernardim Ribeiro": "Escritor, c. 1482–c. 1552",
    "Sá de Miranda": "Poeta, c. 1481–1558",
    "António Ferreira": "Poeta, 1528–1569",
    "Padre António Vieira": "Orador e escritor, 1608–1697",
    "Almeida Garrett": "Escritor e político, 1799–1854",
    "Alexandre Herculano": "Escritor e historiador, 1810–1877",
    "Camilo Castelo Branco": "Escritor, 1825–1890",
    "Eça de Queirós": "Escritor, 1845–1900",
    "Antero de Quental": "Poeta, 1842–1891",
    "Cesário Verde": "Poeta, 1855–1886",
    "Júlio Dinis": "Escritor, 1839–1871",
    "Guerra Junqueiro": "Poeta, 1850–1923",
    "Bocage": "Poeta, 1765–1805",
    "Marquês de Pombal": "Estadista, 1699–1782",
    "Nuno Álvares Pereira": "Condestável, 1360–1431",
    "D. Afonso de Albuquerque": "Vice-rei da Índia, 1453–1515",
    "Conde de Castelo Melhor": "Estadista, 1636–1720",
    "Conde da Ericeira": "Estadista e escritor, 1632–1690",
    "Pedro Nunes": "Matemático, 1502–1578",
    "Garcia de Orta": "Naturalista, c. 1501–1568",
    "Damião de Góis": "Humanista, 1502–1574",
    "Duarte Barbosa": "Explorador e escritor, c. 1480–1521",
    "Nuno Gonçalves": "Pintor, séc. XV",
    "Grão Vasco": "Pintor, c. 1475–c. 1542",
    "Josefa de Óbidos": "Pintora, 1630–1684",
    "Domingos Sequeira": "Pintor, 1768–1837",
    "Machado de Castro": "Escultor, 1731–1822",
}
