"""Portuguese monuments and landmarks."""

MONUMENTS = [
    "Torre de Belém",
    "Mosteiro dos Jerónimos",
    "Palácio da Pena",
    "Castelo de São Jorge",
    "Ponte 25 de Abril",
    "Sé de Lisboa",
    "Universidade de Coimbra",
    "Convento de Cristo",
    "Mosteiro de Alcobaça",
    "Mosteiro da Batalha",
    "Palácio da Bolsa",
    "Sé do Porto",
    "Ponte Dom Luís I",
    "Santuário do Bom Jesus do Monte",
    "Castelo de Guimarães",
    "Torre dos Clérigos",
    "Aqueduto das Águas Livres",
    "Palácio Nacional de Mafra",
    "Palácio Nacional de Sintra",
    "Castelo de Almourol",
    "Castelo de Óbidos",
    "Fortaleza de Sagres",
    "Sé de Braga",
    "Ruínas de Conímbriga",
    "Templo Romano de Évora",
    "Palácio de Queluz",
    "Castelo dos Mouros",
    "Padrão dos Descobrimentos",
    "Oceanário de Lisboa",
    "Livraria Lello",
    "Ponte Vasco da Gama",
    "Sé de Évora",
    "Castelo de Silves",
    "Forte de São João Baptista",
    "Panteão Nacional",
    "Elevador de Santa Justa",
    "Castelo de Leiria",
    "Palácio de Mateus",
    "Citânia de Briteiros",
    "Sé Velha de Coimbra",
    "Castelo de Bragança",
    "Forte da Graça",
    "Praça do Comércio",
    # New additions
    "Palácio Nacional da Ajuda",
    "Basílica da Estrela",
    "Convento de Mafra",
    "Castelo de Tomar",
    "Castelo de Monsanto",
    "Castelo de Marvão",
    "Muralhas de Elvas",
    "Igreja de São Roque",
    "Palácio de Monserrate",
    "Quinta da Regaleira",
    "Jardim Botânico de Coimbra",
    "Farol da Berlenga",
    "Cabo da Roca",
    "Arco da Rua Augusta",
    "Estação de São Bento",
    "Museu Nacional do Azulejo",
    "Mosteiro de Tibães",
    "Castelo de Palmela",
    "Forte de São Julião da Barra",
    "Capela dos Ossos",
]

# Map Portuguese names to English Wikipedia article titles
WIKIPEDIA = {
    "Torre de Belém": "Belém Tower",
    "Mosteiro dos Jerónimos": "Jerónimos Monastery",
    "Palácio da Pena": "Pena Palace",
    "Castelo de São Jorge": "São Jorge Castle",
    "Ponte 25 de Abril": "25 de Abril Bridge",
    "Sé de Lisboa": "Lisbon Cathedral",
    "Universidade de Coimbra": "University of Coimbra",
    "Convento de Cristo": "Convent of Christ (Tomar)",
    "Mosteiro de Alcobaça": "Alcobaça Monastery",
    "Mosteiro da Batalha": "Batalha Monastery",
    "Palácio da Bolsa": "Palácio da Bolsa",
    "Sé do Porto": "Porto Cathedral",
    "Ponte Dom Luís I": "Dom Luís I Bridge",
    "Santuário do Bom Jesus do Monte": "Bom Jesus do Monte",
    "Castelo de Guimarães": "Guimarães Castle",
    "Torre dos Clérigos": "Clérigos Tower",
    "Aqueduto das Águas Livres": "Águas Livres Aqueduct",
    "Palácio Nacional de Mafra": "Palace of Mafra",
    "Palácio Nacional de Sintra": "Palace of Sintra",
    "Castelo de Almourol": "Almourol Castle",
    "Castelo de Óbidos": "Castle of Óbidos",
    "Fortaleza de Sagres": "Fortress of Sagres",
    "Sé de Braga": "Braga Cathedral",
    "Ruínas de Conímbriga": "Conímbriga",
    "Templo Romano de Évora": "Temple of Diana (Évora)",
    "Palácio de Queluz": "Palace of Queluz",
    "Castelo dos Mouros": "Castle of the Moors",
    "Padrão dos Descobrimentos": "Padrão dos Descobrimentos",
    "Oceanário de Lisboa": "Lisbon Oceanarium",
    "Livraria Lello": "Livraria Lello",
    "Ponte Vasco da Gama": "Vasco da Gama Bridge",
    "Sé de Évora": "Évora Cathedral",
    "Castelo de Silves": "Castle of Silves",
    "Forte de São João Baptista": "Fort of São João Baptista (Berlengas)",
    "Panteão Nacional": "National Pantheon (Portugal)",
    "Elevador de Santa Justa": "Santa Justa Lift",
    "Castelo de Leiria": "Castle of Leiria",
    "Palácio de Mateus": "Mateus Palace",
    "Citânia de Briteiros": "Citânia de Briteiros",
    "Sé Velha de Coimbra": "Old Cathedral of Coimbra",
    "Castelo de Bragança": "Castle of Bragança",
    "Forte da Graça": "Fort of Graça",
    "Praça do Comércio": "Praça do Comércio",
    "Palácio Nacional da Ajuda": "Ajuda National Palace",
    "Basílica da Estrela": "Estrela Basilica",
    "Convento de Mafra": "Palace of Mafra",
    "Castelo de Tomar": "Castle of Tomar",
    "Castelo de Monsanto": "Monsanto (Idanha-a-Nova)",
    "Castelo de Marvão": "Marvão Castle",
    "Muralhas de Elvas": "Garrison Border Town of Elvas and its Fortifications",
    "Igreja de São Roque": "Church of São Roque",
    "Palácio de Monserrate": "Palace of Monserrate",
    "Quinta da Regaleira": "Quinta da Regaleira",
    "Jardim Botânico de Coimbra": "Botanical Garden of the University of Coimbra",
    "Farol da Berlenga": "Berlengas",
    "Cabo da Roca": "Cabo da Roca",
    "Arco da Rua Augusta": "Rua Augusta Arch",
    "Estação de São Bento": "São Bento railway station",
    "Museu Nacional do Azulejo": "National Tile Museum",
    "Mosteiro de Tibães": "Monastery of Tibães",
    "Castelo de Palmela": "Castle of Palmela",
    "Forte de São Julião da Barra": "Fort of São Julião da Barra",
    "Capela dos Ossos": "Chapel of Bones",
}

LOCATIONS = {
    "Torre de Belém": "Lisboa",
    "Mosteiro dos Jerónimos": "Lisboa",
    "Palácio da Pena": "Sintra",
    "Castelo de São Jorge": "Lisboa",
    "Ponte 25 de Abril": "Lisboa",
    "Sé de Lisboa": "Lisboa",
    "Universidade de Coimbra": "Coimbra",
    "Convento de Cristo": "Tomar",
    "Mosteiro de Alcobaça": "Alcobaça",
    "Mosteiro da Batalha": "Batalha",
    "Palácio da Bolsa": "Porto",
    "Sé do Porto": "Porto",
    "Ponte Dom Luís I": "Porto",
    "Santuário do Bom Jesus do Monte": "Braga",
    "Castelo de Guimarães": "Guimarães",
    "Torre dos Clérigos": "Porto",
    "Aqueduto das Águas Livres": "Lisboa",
    "Palácio Nacional de Mafra": "Mafra",
    "Palácio Nacional de Sintra": "Sintra",
    "Castelo de Almourol": "Vila Nova da Barquinha",
    "Castelo de Óbidos": "Óbidos",
    "Fortaleza de Sagres": "Sagres",
    "Sé de Braga": "Braga",
    "Ruínas de Conímbriga": "Condeixa-a-Nova",
    "Templo Romano de Évora": "Évora",
    "Palácio de Queluz": "Queluz",
    "Castelo dos Mouros": "Sintra",
    "Padrão dos Descobrimentos": "Lisboa",
    "Oceanário de Lisboa": "Lisboa",
    "Livraria Lello": "Porto",
    "Ponte Vasco da Gama": "Lisboa",
    "Sé de Évora": "Évora",
    "Castelo de Silves": "Silves",
    "Forte de São João Baptista": "Berlengas",
    "Panteão Nacional": "Lisboa",
    "Elevador de Santa Justa": "Lisboa",
    "Castelo de Leiria": "Leiria",
    "Palácio de Mateus": "Vila Real",
    "Citânia de Briteiros": "Guimarães",
    "Sé Velha de Coimbra": "Coimbra",
    "Castelo de Bragança": "Bragança",
    "Forte da Graça": "Elvas",
    "Praça do Comércio": "Lisboa",
    "Palácio Nacional da Ajuda": "Lisboa",
    "Basílica da Estrela": "Lisboa",
    "Convento de Mafra": "Mafra",
    "Castelo de Tomar": "Tomar",
    "Castelo de Monsanto": "Monsanto",
    "Castelo de Marvão": "Marvão",
    "Muralhas de Elvas": "Elvas",
    "Igreja de São Roque": "Lisboa",
    "Palácio de Monserrate": "Sintra",
    "Quinta da Regaleira": "Sintra",
    "Jardim Botânico de Coimbra": "Coimbra",
    "Farol da Berlenga": "Berlengas",
    "Cabo da Roca": "Sintra",
    "Arco da Rua Augusta": "Lisboa",
    "Estação de São Bento": "Porto",
    "Museu Nacional do Azulejo": "Lisboa",
    "Mosteiro de Tibães": "Braga",
    "Castelo de Palmela": "Palmela",
    "Forte de São Julião da Barra": "Oeiras",
    "Capela dos Ossos": "Évora",
}
