"""Portuguese native and iconic wildlife and plants."""

ANIMALS = [
    # Marine
    "Golfinho-roaz",
    "Sardinha",
    "Cavalo-marinho",
    "Polvo",
    "Lula",
    "Caranguejo",
    "Atum",
    "Peixe-espada",
    "Bacalhau",
    "Mexilhão",
    "Amêijoa",
    "Percebe",
    "Lagosta",
    # Birds
    "Cegonha-branca",
    "Águia-imperial-ibérica",
    "Flamingo",
    "Pega-azul",
    "Andorinha",
    "Pardal",
    "Melro",
    "Poupa",
    "Coruja-das-torres",
    "Garça-real",
    "Cagarra",
    "Milhafre",
    "Pintassilgo",
    "Chapim-azul",
    # Mammals
    "Lince-ibérico",
    "Lobo-ibérico",
    "Cabra-montês",
    "Javali",
    "Raposa",
    "Texugo",
    "Lontra",
    "Gineta",
    "Gato-bravo",
    "Veado",
    "Morcego",
    "Ouriço-cacheiro",
    "Coelho-bravo",
    "Foca-monge",
    # Reptiles & Amphibians
    "Camaleão",
    "Lagartixa",
    "Cobra-rateira",
    "Víbora-cornuda",
    "Cágado",
    "Salamandra-lusitânica",
    "Rã-ibérica",
    "Tritão-marmoreado",
]

# Map to English Wikipedia articles
ANIMAL_WIKIPEDIA = {
    "Golfinho-roaz": "Common bottlenose dolphin",
    "Sardinha": "European pilchard",
    "Cavalo-marinho": "Seahorse",
    "Polvo": "Octopus",
    "Lula": "European squid",
    "Caranguejo": "Crab",
    "Atum": "Atlantic bluefin tuna",
    "Peixe-espada": "Black scabbardfish",
    "Bacalhau": "Atlantic cod",
    "Mexilhão": "Mussel",
    "Amêijoa": "Clam",
    "Percebe": "Goose barnacle",
    "Lagosta": "Spiny lobster",
    "Cegonha-branca": "White stork",
    "Águia-imperial-ibérica": "Spanish imperial eagle",
    "Flamingo": "Greater flamingo",
    "Pega-azul": "Iberian magpie",
    "Andorinha": "Barn swallow",
    "Pardal": "House sparrow",
    "Melro": "Common blackbird",
    "Poupa": "Eurasian hoopoe",
    "Coruja-das-torres": "Barn owl",
    "Garça-real": "Grey heron",
    "Cagarra": "Cory's shearwater",
    "Milhafre": "Black kite",
    "Pintassilgo": "European goldfinch",
    "Chapim-azul": "Eurasian blue tit",
    "Lince-ibérico": "Iberian lynx",
    "Lobo-ibérico": "Iberian wolf",
    "Cabra-montês": "Iberian ibex",
    "Javali": "Wild boar",
    "Raposa": "Red fox",
    "Texugo": "European badger",
    "Lontra": "Eurasian otter",
    "Gineta": "Common genet",
    "Gato-bravo": "European wildcat",
    "Veado": "Red deer",
    "Morcego": "Bat",
    "Ouriço-cacheiro": "European hedgehog",
    "Coelho-bravo": "European rabbit",
    "Foca-monge": "Mediterranean monk seal",
    "Camaleão": "Mediterranean chameleon",
    "Lagartixa": "Wall lizard",
    "Cobra-rateira": "Montpellier snake",
    "Víbora-cornuda": "Lataste's viper",
    "Cágado": "European pond turtle",
    "Salamandra-lusitânica": "Lusitanian fire salamander",
    "Rã-ibérica": "Iberian frog",
    "Tritão-marmoreado": "Marbled newt",
}

PLANTS = [
    # Trees
    "Sobreiro",
    "Azinheira",
    "Oliveira",
    "Pinheiro-manso",
    "Pinheiro-bravo",
    "Eucalipto",
    "Castanheiro",
    "Medronheiro",
    "Alfarrobeira",
    "Carvalho-português",
    "Loureiro",
    "Figueira",
    "Amendoeira",
    "Cipreste",
    # Flowers & shrubs
    "Esteva",
    "Rosmaninho",
    "Alfazema",
    "Tomilho",
    "Urze",
    "Giesta",
    "Camelia",
    "Hortênsia dos Açores",
    "Flor-de-sal",
    "Cravo",
    "Murta",
    "Madressilva",
    # Vines & crops
    "Videira",
    "Laranjeira",
    "Limoeiro",
]

PLANT_WIKIPEDIA = {
    "Sobreiro": "Quercus suber",
    "Azinheira": "Quercus ilex",
    "Oliveira": "Olive (tree)",
    "Pinheiro-manso": "Stone pine",
    "Pinheiro-bravo": "Pinus pinaster",
    "Eucalipto": "Eucalyptus globulus",
    "Castanheiro": "Sweet chestnut",
    "Medronheiro": "Arbutus unedo",
    "Alfarrobeira": "Carob",
    "Carvalho-português": "Quercus faginea",
    "Loureiro": "Laurus nobilis",
    "Figueira": "Common fig",
    "Amendoeira": "Almond",
    "Cipreste": "Mediterranean cypress",
    "Esteva": "Cistus ladanifer",
    "Rosmaninho": "Lavandula stoechas",
    "Alfazema": "Lavandula angustifolia",
    "Tomilho": "Thymus vulgaris",
    "Urze": "Erica",
    "Giesta": "Cytisus",
    "Camelia": "Camellia japonica",
    "Hortênsia dos Açores": "Hydrangea macrophylla",
    "Flor-de-sal": "Limonium",
    "Cravo": "Dianthus",
    "Murta": "Myrtus",
    "Madressilva": "Lonicera",
    "Videira": "Grape",
    "Laranjeira": "Orange (fruit)",
    "Limoeiro": "Lemon",
}

ALL_ANIMALS = ANIMALS
ALL_PLANTS = PLANTS
